check50:
  checks:
  hello:
  - run: python3 hello.py
    stout: Hello, world!
    exit: 0
  nzquizold:
  - run: python3 nzquiz.py
    stdout: What is your name?
    stdin: simon
    stdin: 40
    stdin: n
    exit: 0
