check50:
  checks:
    quit:
      - run: python3 nzquiz.py
        stdout: What is your name? 
        stdin: Simon
        stdout: How old are you? 
        stdin: 55
        stdin: N
        exit: 0
